In [0]:
1 + 2

3

In [0]:
(1 + 2 * 3 - 4) / 5

0.6

In [0]:
2 ** 8

256

In [0]:
a=1.5

In [0]:
a="learning"

In [0]:
b='abc'

In [0]:
type(100)

int

In [0]:
type(100.1)

float

In [0]:
a=(1, 2, 3)

In [0]:
 b=(2,)

In [0]:
False

False

In [0]:
b=(2,)
b[0]+1

3

In [0]:
x = 1 / 3
x
y = 2 / 3
y

0.6666666666666666

In [0]:
x = 1 / 3
print(x)
y = 2 / 3
print(y)
print('x= ' + str(x))
print('weight = {0} kg'.format(x))

0.3333333333333333
0.6666666666666666
x= 0.3333333333333333
weight = 0.3333333333333333 kg


In [0]:
x = 1 / 3
y = 1 / 7
z = 1 / 4
print ('weight : {0} kg {1} kg {2} kg'.format(x, y, z))

weight : 0.3333333333333333 kg 0.14285714285714285 kg 0.25 kg


In [0]:
print('weight: {0:.2f} kg, y={1:.2f} kg, z={2:.2f} kg'.format(x,y,z))

weight: 0.33 kg, y=0.14 kg, z=0.25 kg


In [0]:
x = [1, 1, 2, 3, 5] # list의 정의
print(x) # 표시


[1, 1, 2, 3, 5]


In [0]:
x[0]

1

In [0]:
x[2]

2

In [0]:
print(type(x))
print(type(x[0]))


<class 'list'>
<class 'int'>


In [0]:
s=['SUN', 1, 'MON', 2]
print(type(s[0]))
print(type(s[1]))


<class 'str'>
<class 'int'>


In [0]:
a=[[1, 2, 3], [4, 5, 6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [0]:
a=[[1, 2, 3], [4, 5, 6]]
print(a[0][1])

2


In [0]:
x=[1, 1, 2, 3, 5]
x[3] = 100
print(x)

[1, 1, 2, 100, 5]


In [0]:
x=[1, 1, 2, 3, 5]
len(x)

5

In [0]:
y = range(5, 10)
print(y[0], y[1], y[2], y[3], y[4])


5 6 7 8 9


In [0]:
print(y)

range(5, 10)


In [0]:
z=list(range(5, 10))
print(z)


[5, 6, 7, 8, 9]


In [0]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [0]:
a=(1, 2, 3)
print(a)


(1, 2, 3)


In [0]:
a[1]

2

In [0]:
type(a)

tuple

In [0]:
a = (1)
type(a)
    

int

In [0]:
a = (1,)
type(a)


tuple

In [0]:
x = 11
if x > 10:
    print('x is ') # ... (A1)
    print('        larger than 10.') # ... (A2)
else:
    print('x is smaller than 11') # ... (B1) 


x is 
        larger than 10.


In [0]:
x > 10

True

In [0]:
type(x > 10)

bool

In [0]:
x = 15
if 10 <= x and x <= 20:
    print('x is between 10 and 20.')


x is between 10 and 20.


In [0]:
for i in [1, 2, 3]:
    print(i)


1
2
3


In [0]:
num = [2, 4, 6, 8, 10]
for i in range(len(num)):
    num[i] = num[i] * 2
print(num)


[4, 8, 12, 16, 20]


In [0]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

## `numpy`

벡터와 행렬을 처리하려면 `numpy` 라이브러리를 사용한다.
`numpy` 라이브러리는 `np`라는 이름으로 사용하는 것이 관례이다.

In [0]:
import numpy as np

`list`를 `numpy` 배열(array)로 변환하면 1차원 배열 즉, 벡터가 된다.

In [0]:
x=np.array([1, 2, 3])
x

array([1, 2, 3])

In [0]:
print(x)

[1 2 3]


In [0]:
y=np.array([4, 5, 6])
print(x + y)

[5 7 9]


## 연습 문제

1. `list` [1, 2, 3]과 [4, 5, 6]을 더하면 어떤 결과가 나오는가?

In [0]:
a = [1, 2, 3]
b = [4, 5, 6, 7]
a + b

[1, 2, 3, 4, 5, 6, 7]

In [0]:
type(x)

numpy.ndarray

`numpy` 배열의 요소를 참조할 때는 `list`와 같이 `[]`를 사용한다.
`[]`에는 요소의 위치를 나타내는 **인덱스(index)**를  기재한다.
인덱스는 0부터 시작한다.

In [0]:
x[0]

1

In [0]:
x[-2]

2

In [0]:
x[0] = 100
print(x)

[100   2   3]


`range()` 함수로 규칙적인 정수 등차 수열을 만들 수 있다.
`numpy`의 `arange()` 함수로 정수와 실수 등차 수열을 만들 수 있다.

```python
arange(start, stop, step)
```

In [0]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [0]:
print(np.arange(5, 10))

[5 6 7 8 9]


In [0]:
np.arange(0.1, 2.5, 0.2)

array([0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3])

In [0]:
j=np.array([4, 5, 6])
for i in np.arange(1,4):
    print(i)
    print(i + j)

1
[5 6 7]
2
[6 7 8]
3
[7 8 9]


파이썬 변수는 기본적으로 객체의 주소(참조)를 저장하고 있다.
그리고 변수를 다른 변수에 저장하면 객체의 주소가 저장되기 때문에 결국 동일한 객체를 가르키게 된다.

`numpy` 배열 객체의 복사본을 원하면 `copy()` 메소드를 사용해야 한다.

In [0]:
a = np.array(range(5))
a

array([0, 1, 2, 3, 4])

In [0]:
b = a


In [0]:
b[0] = 100
b

array([100,   1,   2,   3,   4])

In [0]:
a

array([100,   1,   2,   3,   4])

In [0]:
a = np.array([1, 1])
b = a
print('a =' + str(a))
print('b =' + str(b))
b[0] = 100
print('b =' + str(b))
print('a =' + str(a))

a =[1 1]
b =[1 1]
b =[100   1]
a =[100   1]


In [0]:
a = np.array([1, 1])
b = a.copy()
print('a =' + str(a))
print('b =' + str(b))
b[0] = 100
print('b =' + str(b))
print('a =' + str(a))


a =[1 1]
b =[1 1]
b =[100   1]
a =[1 1]


`list`의 `list`를 `numpy` 배열로 변환하면 2차원 행렬이 된다.

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)


[[1 2 3]
 [4 5 6]]


In [0]:
np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]).shape

(2, 2, 3)

`numpy` 배열의 `shape` 속성(attribute)으로 각 차원의 요소 수를 알 수 있다.
`shape` 속성의 결과는 `tuple`이다.

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x.shape

(2, 3)

In [0]:
x.ndim

2

`tuple`을 `unpacking`하여 각 차원의 요소 수를 별도로 접근할 수 있다.

In [0]:
w, h = x.shape
print(w)
print(h)

2
3


In [0]:
type(x.shape)

tuple

In [0]:
w, h = x.shape
print(w)
print(h)


2
3


2차원 행렬의 요소에 접근하기 위해서는 `[]`에 두 개의 인덱스를 기재한다.

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[1, 2]


6

In [0]:
x[1][2]

6

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[0, 2]

3

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[1, 2] = 100
print(x)

[[  1   2   3]
 [  4   5 100]]


특별한 구조를 가진 행렬을 쉽게 만들 수 있는 함수가 준비되어 있다.

In [0]:
# 10개 요소가 모두 0인 벡터 
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [0]:
# 모든 요소가 0인 2x10 2차원 배열(행렬)
print(np.zeros((2, 10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [0]:
# 모든 요소가 1인 2x10 2차원 배열
print(np.ones((2, 10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [0]:
# 모든 요소가 (0, 1) 사이의 난수인 2x3 2차원 배열
x = np.random.rand(2, 3)
print(x)

[[0.17464133 0.70325974 0.19336291]
 [0.87672521 0.66468319 0.75461912]]


## 연습 문제

1. `np.random.randn()` 함수로 모든 요소가 표준 정규 분포 난수인 4x5x6 3차원 배열을 만드시오.

2. `np.random.randint()` 함수로 요소가 1과 100 사이의 정수 중에서 랜덤하게 추출한 난수인 3x4x5x6 4차원 배열을 만드시오.

In [0]:
d4 = np.random.randint(1, 101, size=(3, 4, 5, 6))
print(d4)

[[[[72  3 62 59  8 34]
   [86 21 73 45 20 37]
   [41 10 37 34 77 74]
   [56 84 79 38 38 36]
   [29 97 23  6 92 42]]

  [[ 4 56 33 12 15 36]
   [14 94 83 75 61 98]
   [49 44  7 54 45 62]
   [87  7 41 18 18 47]
   [84 14 62 28 95 51]]

  [[87 31 91 91 19 95]
   [ 9 92 22 11  2 71]
   [77 20 98 74 88 17]
   [90 46 93 61 32 30]
   [71 43 77 66  2 74]]

  [[15 44 38  6 47 91]
   [42 90 76 50 65 54]
   [78 45 38 64 72 43]
   [15 77 93  5  9 53]
   [74 10 75 20 41 51]]]


 [[[78 80 93 20 13 69]
   [62 20 51 79 72 83]
   [71 22 94 35  9 83]
   [60 34 34 58 43 44]
   [17 73 45 53 43 95]]

  [[35 12 96 83  8 77]
   [33 32 43 28 60 83]
   [39 82 23 76  9 87]
   [28 73 85 87 86  9]
   [13 58 86  6 71 88]]

  [[51 55 91  1 15 38]
   [24 95 41 78  4 26]
   [12 20 42 51 97 98]
   [18 63 90 67 67 56]
   [54 52 81 24 61 92]]

  [[56 26 37 64 85 65]
   [78 27 74 57 55  2]
   [50 81 14 25 59 24]
   [80 90 89  3  3 38]
   [ 4 60 63 86 42 46]]]


 [[[42 72  3 47 47 95]
   [84 91 13 92 86 11]
   [91 24 46 7

In [0]:
data = np.random.randn(4, 5, 6)
print(data)

[[[-1.28050295 -0.00249238  0.18052501 -0.28400261 -0.67117963
    0.44260285]
  [-0.17628779  1.11968717  0.40441235 -1.44864462 -0.88334701
   -0.4680094 ]
  [-0.35521804 -1.83309289  1.55372825  0.31913894 -0.39122397
    0.36037202]
  [-0.98226997  0.06462347  0.09821774  0.79596723  0.71449542
   -0.83960207]
  [-0.65021798  1.17104172 -0.60374566  1.18189143  0.17833756
   -0.5321926 ]]

 [[ 1.08934236  0.25401653  0.57457046 -0.07276219 -0.0440186
    0.45238072]
  [ 1.15446338  1.47891136  1.75456153 -0.95793957  0.13627855
   -0.24402452]
  [-0.61425019  1.08323684 -0.33592982  1.51931962  1.25519185
   -2.08463526]
  [-1.59945066 -0.37759774 -1.00416502 -1.21069636 -0.67592999
    0.86874788]
  [ 1.04722708  0.32135766 -0.94409065  0.01042461 -0.27860691
    0.43958433]]

 [[ 0.49457214 -0.05144114 -1.15173156 -0.0707424   0.62103933
    1.45063356]
  [ 0.07312718 -0.70167833  0.2917367  -2.21615577 -0.45392451
    0.1033654 ]
  [-0.82806904 -0.37089144 -0.99626484  0.6956021

`reshape()` 메소드를 이용하면 numpy 배열의 차원과 각 차원의 요소 수를 변경할 수 있다.
전체 요소의 수를 변경할 수는 없다.

In [0]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [0]:
a.shape

(10,)

In [0]:
b = a.reshape(2, 5)

In [0]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [0]:
b.reshape(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
b.shape[0]

2

## `numpy` 배열 간의 연산

기본적으로 차원과 각 차원의 요소 수은 배열 간에 사칙 연산을 수행할 수 있다.

In [0]:
import numpy as np

x = np.array([[4, 4, 4], [8, 8, 8]])
y = np.array([[1, 1, 1], [2, 2, 2]])
print(x + y)

[[ 5  5  5]
 [10 10 10]]


In [0]:
print(x, y)

[[4 4 4]
 [8 8 8]] [[1 1 1]
 [2 2 2]]


스칼라와 배열 간의 연산은 가능하다.

In [0]:
x + 2

array([[ 6,  6,  6],
       [10, 10, 10]])

In [0]:
x = np.array([[4, 4, 4], [8, 8, 8]])
print(10 * x)

[[40 40 40]
 [80 80 80]]


배열에 함수를 적용하면 배열의 각 요소에 함수를 적용한 결과의 배열을 얻는다.
자주 사용하는 함수로는 `np.sqrt()`, `np.log()`, `np.round()`, `np.exp()` 등이 있다.

In [0]:
x = np.array([[4, 4, 4], [8, 8, 8]])
print(np.exp(x))

[[  54.59815003   54.59815003   54.59815003]
 [2980.95798704 2980.95798704 2980.95798704]]


배열에 저장된 값을 자료로 하여 통계치를 계산하는 함수도 있다.
`np.mean()`, `np.std()`, `np.min()`, `np.max()` 등등

In [0]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(np.mean(a))               # 배열의 모든 요소를 이용하여 평균을 계산한다.

print(np.mean(a, axis=0))       # 열별로 평균을 계산한다.

print(np.mean(a, axis=1))       # 행별로 평균을 계산한다.

[[1 2 3]
 [4 5 6]]
3.5
[2.5 3.5 4.5]
[2. 5.]


## broadcasting

shape이 다른 배열 간의 연산이 가능하도록 배열의 shape을 자동으로 변환하여 연산하는 기능을 말한다.
이때 요수의 수가 1인 차원 방향으로 배열을 반복하여 shape를 변환한다.


In [0]:
col_means = np.mean(a, axis=0)
print(a.shape)
print(col_means.shape)

print(col_means)
print(a)

(2, 3)
(3,)
[2.5 3.5 4.5]
[[1 2 3]
 [4 5 6]]


In [0]:
a - col_means  # col_means를 1x3로 생각하고 이를 반복하여 2x3로 만든 다음 연산한다.

array([[-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5]])

In [0]:
a * col_means

array([[ 2.5,  7. , 13.5],
       [10. , 17.5, 27. ]])

In [0]:
a - col_means

array([[-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5]])

In [0]:
a + col_means

array([[ 3.5,  5.5,  7.5],
       [ 6.5,  8.5, 10.5]])

In [0]:
row_means = np.mean(a, axis=1)
print(a.shape)
print(row_means.shape)

print(row_means)
print(a)

(2, 3)
(2,)
[2. 5.]
[[1 2 3]
 [4 5 6]]


In [0]:
a - row_means # row_means를 1x2로 생각하고 이를 반복해도 a와 같은 2x3로 반들 수 없다.
              # 따라서 braodcasting으로도 계산할 수 없으므로 오류가 발생한다.

ValueError: ignored

In [0]:
a * row_means

ValueError: ignored

In [0]:
data = np.array([[[1, 2], [3,4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(data)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [0]:
np.sum(data, axis=0)

array([[15, 18],
       [21, 24]])

In [0]:
np.sum(data, axis=1)

array([[ 4,  6],
       [12, 14],
       [20, 22]])

In [0]:
np.sum(data, axis=2)

array([[ 3,  7],
       [11, 15],
       [19, 23]])

## 연습 문제

1. 표준 정규분포 난수를 발생하여 5x10 행렬 data를 만드시오.

2. 행렬 data의 행별, 열별 평균, 표준편차, 분산, 합, 최대값, 최소값을 구하시오.

3. 행렬 data를 열별로 표준화하시오. (표준화는 평균을 빼고 표준편차로 나누는 것이다.)

4. 행렬 data를 열별로 정규화하시오. (정규화는 최소값을 뺀 다음 최대값과 최소값을 차이를 나누는 것이다.)

In [0]:
data = np.random.randn(5,10)
cmean = np.mean(data, axis=0)
cstd = np.std(data, axis=0)
csum = np.sum(data, axis=0)
cmax = np.max(data, axis=0)
cmin = np.min(data, axis=0)


std_data = (data - cmean) / cstd
norm_data = (data - cmin) / ( cmax - cmin)


## 행렬 곱 연산

내적(inner product) 또는 scalar product라고 한다. dot product

In [2]:
import numpy as np
v = np.array([[1, 2, 3], [4, 5, 6]])  # 2x3
w = np.array([[1, 1], [2, 2], [3, 3]]) # 3 x 2 
print(v.dot(w))
w.dot(v)

[[14 14]
 [32 32]]


array([[ 5,  7,  9],
       [10, 14, 18],
       [15, 21, 27]])

## 연습 문제

1. 표준 정규 분포 난수를 요소로 하는 4x4, 4x2, 3x4, 4x1 행렬을 만들고 이들간의 행렬 곱을 계산하시오.

In [3]:
x = np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


`numpy` 배열에도 slicing을 사용할 수 있다.
slicing은 배열의 일부분 원소를 추출하기 위한 도구이다.




In [0]:
print(x[5:])

[5 6 7 8 9]


In [0]:
print(x[3:8])

[3 4 5 6 7]


In [0]:
print(x[3:8:2])

[3 5 7]


In [0]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [0]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(y)
print(y[:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]]


배열에 비교 연산을 수행하면 배열의 각 원소에 비교 연산을 수행한 논리값이 저장된 배열을 얻는다.
결과로 얻어지는 논리값 배열의 shape은 원 배열과 동일하다.

In [0]:
x = np.array([1, 1, 2, 3, 5, 8, 13])
x > 3

array([False, False, False, False,  True,  True,  True])

배열과 동일한 shape의 논리값 배열을 인덱스로 사용하면 True에 대응하는 요소만 들어 있는 배열을 결과로 얻는다.

Slicing과 같이 배열의 원소 일부분을 추출하는 방법으로 생각할 수 있다.

In [0]:
x[x > 3]

array([ 5,  8, 13])

In [0]:
x[x > 3] = 999
print(x)

[  1   1   2   3 999 999 999]


In [0]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

In [0]:
np.random.randint(5)

0

In [0]:
np.random.randint(5, 10, (3, 2))

array([[9, 5],
       [6, 8],
       [5, 5]])

## 함수의 정의와 호출(실행)

In [0]:
# 매개변수가 없는 함수의 정의
def my_func1():
    print('Hi!')
# 함수 my_func1()의 정의는 여기까지
my_func1() # 함수를 실행

Hi!


In [5]:
# 매개변수가 2개인 함수의 정의
# 매개변수는 함수를 호출하는 측이 함수에 데이터를 전달하는 통로이다
# return 문장은 함수가 함수를 호출하는 측에 데이터(실행 결과)를 전달한다.

def my_func2(a, b):
    c = a + b
    return c       # 반환값 또는 출력값(교재)라고 한다.


my_func2(1, 2)

3

return 문장으로 여러 개의 값을 반환하면 이 값을 요소로 하는 tuple이 생성되어 전달된다. (packing)

In [0]:
def my_func3(D):
    m = np.mean(D)
    s = np.std(D)
    return m, s

문자열의 format() 메소드: 문자열 내에 지정한 값을 지정한 형식으로 출력해준다. 기본적으로 문자열 내의 {}에 해당하는 위치에 format() 메소드의 인자를 출력한다. {}에는 어떤 인자를 어떤 형식으로 출력할 것이지 기재한다.

In [7]:
data=np.random.randn(100)
data_mean, data_std = my_func3(data)   # unpacking
print('mean:{0:3.2f}, std:{1:3.2f}'.format(data_mean, data_std))
# {3:5d}, {5:10s}


mean:0.06, std:0.90


In [0]:
output = my_func3(data)
print(output)
print(type(output))
print('mean:{0:3.2f}, std:{1:3.2f}'.format(output[0], output[1]))

(0.002269224053547081, 1.0551678713659625)
<class 'tuple'>
mean:0.00, std:1.06


## `numpy` 배열의 저장과 적재

`np.save()` 함수를 이용하여 `numpy` 배열을 파일에 저장하고, `np.load()` 함수를 이용하여 파일에 저장된 `numpy` 배열을 읽어 들일 수 있다.

`numpy` 배열을 저장한 파일의 기본 확장자는 `npy`이다.

In [0]:
data = np.random.randn(5)
print(data)
np.save('datafile.npy', data)  # numpy 배열을 파일에 저장
data = []                      # 데이터 삭제(빈 list로 만듬), del data를 사용하면 객체를 삭제
print(data)
data = np.load('datafile.npy') # 파일에 저장된 numpy 배열을 프로그램 내로 읽어 들인다.
print(data)

[ 0.28997285  0.34626757 -0.66263271 -1.07081366 -0.2590175 ]
[]
[ 0.28997285  0.34626757 -0.66263271 -1.07081366 -0.2590175 ]


`np.savez()` 함수를 이용하여 여러 개의 배열을 하나의 파일에 저장할 수 있으며, 한 파일에 저장된 여러 개의 배열을 분리하여 읽어 들일 수 있다.

여러 개의 배열을 하나의 파일에 저장할 때 확장자는 `npz`로 한다.

```python

np.savez('파일이름.npz', 파일내의배열이름=저장할배열이름, ...)
```

In [0]:
data1 = np.array([1, 2, 3])
data2 = np.array([10, 20, 30])
np.savez('datafile2.npz', data1=data1, data2=data2) # 배열 data1, data2를 data1, data2라는 이름으로 파일에 저장한다.
data1 = [] # 데이터 삭제
data2 = []
outfile = np.load('datafile2.npz') # 파일에 저장된 모든 배열을 읽어 들인다.
print(outfile.files) # 읽어 들인 여러 배열의 이름을 조회할 수 있다.
data1 = outfile['data1'] # [] 연산자로 특정 배열을 지정할 수 있다.
data2 = outfile['data2'] # data2 꺼내기
print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]


## 연습문제

1. `pandas.read_csv()` 함수를 이용하여 `https://raw.githubusercontent.com/joongyang/python-for-raw-beginners/master/datasets/decay.csv` [decay 자료](https://raw.githubusercontent.com/joongyang/python-for-raw-beginners/master/datasets/decay.csv)를 `DataFrame` 객체로 읽어 들인 다음 `DataFrame` 객체의 `values` 속성의 타입(자료형)을 알아 보시오.

2. `DataFrame` 객체의 `to_numpy()` 메소드에 대해서 알아보시오.



In [9]:
import pandas as pd
decay = pd.read_csv('https://raw.githubusercontent.com/joongyang/python-for-raw-beginners/master/datasets/decay.csv')
decay.head()

time    emission
0     0  125.000000
1     1  100.248858
2    11   44.713459
3    21   27.998273
4     2   70.000000

In [14]:
np.mean(decay.values, axis=0)

array([15.        , 42.14573588])

In [0]:
decay_arr = decay.to_numpy()

In [16]:
type(decay_arr)

numpy.ndarray

In [17]:
decay_arr

array([[  0.        , 125.        ],
       [  1.        , 100.2488583 ],
       [ 11.        ,  44.71345876],
       [ 21.        ,  27.99827279],
       [  2.        ,  70.        ],
       [ 12.        ,  32.53314287],
       [ 22.        ,  21.88573499],
       [  3.        ,  83.47079531],
       [ 13.        ,  36.64033626],
       [ 23.        ,  14.27396172],
       [  4.        , 100.        ],
       [ 14.        ,  40.15471123],
       [ 24.        ,  13.66596918],
       [  5.        ,  65.90786956],
       [ 15.        ,  23.08029549],
       [ 25.        ,  11.81643542],
       [  6.        ,  66.53371457],
       [ 16.        ,  39.86792844],
       [ 26.        ,  25.18901636],
       [  7.        ,  53.58808673],
       [ 17.        ,  22.84978589],
       [ 27.        ,   8.19564381],
       [  8.        ,  61.33235104],
       [ 18.        ,  35.01464535],
       [ 28.        ,  17.19133663],
       [  9.        ,  43.92743547],
       [ 19.        ,  17.97726709],
 